# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0034_auto_20160929_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(choices=[('Мягкий', 'Мягкий'), ('Жесткий', 'Жесткий')], default='Жесткий', max_length=7),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(default='1'),
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(default='1', upload_to='bookshop/static/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='number',
            field=models.IntegerField(default='1'),
        ),
    ]
